support:
- homeassistant
devices:
- name: Temperatursensor
  id: temperatursensor
  class: DS18B20
- name: Analogsensor
  id: analogsensor
  class: ADS1115
  connection:
    type: i2c
    bus: 1
    interval: 3000
  values:
  - name: A0
    measure: 0+GND
    min: 0
    max: 65535
    scale: 100
    unit: l
  - name: A1
    measure: 1+GND
    min: 0
    max: 65535
    scale: 100
    unit: l
  - name: Abwasser
    measure: 2+GND
    min: 0
    max: 65535
    scale: 100
    unit: l
  - name: Frischwasser
    measure: 3+GND
    min: 0
    max: 65535
    scale: 100
    unit: l
- name: I/O Expander
  id: ioexpander
  class: MCP23017
  connection:
    type: i2c
    bus: 1
    address: 0x20
  pins:
  - name: Output0
    id: 8
    type: out
  - name: Output1
    id: 9
    type: out
  - name: Output2
    id: 10
    type: out
  - name: Output3
    id: 11
    type: out
  - name: Output4
    id: 12
    type: out
  - name: Output5
    id: 13
    type: out
  - name: Output6
    id: 14
    type: out
  - name: Output7
    id: 15
    type: out